### ISSUE TITLE
FileNotFoundError: Can you help me.

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [Fewed/coursera-gui-automation-downloader#1]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Fewed\\Downloads\\bus\\1'

![image](https://user-images.githubusercontent.com/69203685/90968877-4306a300-e50f-11ea-8541-187110eaf08f.png)

**Comment by M-Daeva** [comment]
Simply use path to your download folder (create it before using). For example 'C:\Downloads\course'.
